In [1]:
import pandas as pd
import numpy as np

In [2]:
df2010 = pd.read_csv('2010.csv')
df2011 = pd.read_csv('2011.csv')
df2012 = pd.read_csv('2012.csv')
df2013 = pd.read_csv('2013.csv')
df2014 = pd.read_csv('2014.csv')
df2015 = pd.read_csv('2015.csv')
df2016 = pd.read_csv('2016.csv')
df2017 = pd.read_csv('2017.csv')
df2018 = pd.read_csv('2018.csv')
df2019 = pd.read_csv('2019.csv')

df = [df2010, df2011, df2012, df2013, df2014, df2015, df2016, df2017, df2018, df2019]

for i in range(len(df)):
    df[i] = df[i].rename(columns={'Unnamed: 0':'Dates'})
    df[i]['Dates'] = pd.to_datetime(df[i]['Dates'])
    df[i] = df[i].set_index(['Dates'])

In [30]:
gasList = []
gasUsage = []
coalList = []
coalUsage = []
plantList = []
plantUsage = []
avg = []
maxVals = []
days = {}
years = list(np.arange(10) + 2010)
for i in range(len(df)):
    gasDays = len(list(filter(lambda x : x == 2, df[i]['AVG_PRICE']))) + 1
    coalDays = len(list(filter(lambda x : x == 3, df[i]['AVG_PRICE']))) + 1
    plantDays = len(df[i]) - gasDays - coalDays
    gasList.append(gasDays)
    gasUsage.append(df[i]['CONSUMPTION'][gasDays])
    coalList.append(coalDays)
    coalUsage.append(df[i]['CONSUMPTION'][coalDays + gasDays] - df[i]['CONSUMPTION'][gasDays])
    plantList.append(plantDays)
    plantUsage.append(df[i]['CONSUMPTION'][-1] - df[i]['CONSUMPTION'][coalDays + gasDays])
    avg.append(df[i]['CONSUMPTION'][-1]/len(df[i]))
    maxVals.append(df[i]['AVG_PRICE'][-1])
    days[years[i]] = (gasDays, coalDays, plantDays)

gasAvg = list(np.array(gasUsage)/np.array(gasList))
coalAvg = list(np.array(coalUsage)/np.array(coalList))
plantAvg = list(np.array(plantUsage)/np.array(plantList))

In [31]:
d = {'Years': years, 'Gas Days': gasList, 'Gas Usage': gasUsage, 'Gas Average': gasAvg, 
     'Coal Days': coalList, 'Coal Usage': coalUsage, 'Coal Average': coalAvg, 
     'Plant Days': plantList, 'Plant Usage': plantUsage, 'Plant Average': plantAvg, 
     'Total Average': avg, 'Max Price': maxVals}
df_summary = pd.DataFrame(d)
df_summary = df_summary.append(df_summary.mean(axis=0), ignore_index=True)

In [32]:
df_summary #the last row is the mean for all values, ignore the year

,Years,Gas Days,Gas Usage,Gas Average,Coal Days,Coal Usage,Coal Average,Plant Days,Plant Usage,Plant Average,Total Average,Max Price
0,2010.0,160.0,1318.734240,8.242089,43.0,439.874164,10.229632,162.0,1374.550445,8.484879,8.583997,4.377488
1,2011.0,159.0,1316.810398,8.281826,67.0,456.940804,6.820012,139.0,999.174379,7.188305,7.597056,4.005573
2,2012.0,163.0,1323.790684,8.121415,62.0,471.490455,7.604685,141.0,1209.256910,8.576290,8.209120,4.209301
3,2013.0,150.0,1333.103923,8.887359,71.0,487.410243,6.864933,144.0,1225.711450,8.511885,8.345824,4.232944
4,2014.0,149.0,1344.415499,9.022923,62.0,482.953205,7.789568,154.0,1252.862117,8.135468,8.438989,4.254589
5,2015.0,172.0,1375.010523,7.994247,61.0,479.123063,7.854476,132.0,798.748641,6.051126,7.268170,3.803823
6,2016.0,182.0,1391.137284,7.643611,67.0,471.628548,7.039232,117.0,947.483007,8.098145,7.678276,3.949858
7,2017.0,163.0,1396.068543,8.564838,64.0,473.043675,7.391307,138.0,966.404872,7.002934,7.768540,3.960213
8,2018.0,185.0,1408.720544,7.614706,50.0,481.435602,9.628712,130.0,912.719814,7.020922,7.679112,3.905691
9,2019.0,170.0,1427.730195,8.398413,55.0,481.024444,8.745899,140.0,1033.622307,7.383016,8.061307,4.016465
10,2014.5,165.3,1363.552183,8.277143,60.2,472.492420,7.996846,139.7,1072.053394,7.645297,7.963039,4.071595